#global:

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 60s
  repeat_interval: 60s
  receiver: 'null'

  routes:
  - receiver: 'alertmananger-bot'
    repeat_interval: 60s
    match_re:
      job: blackbox

receivers:

- name: email-me
  email_configs:
  - to: vasulrgdevera@gmail.com
    require_tls: false
    from: team3crashcourse@gmail.com
    smarthost: smtp.gmail.com:465
    auth_username: "team3crashcourse"
    auth_identity: "team3crashcourse"
    auth_password: "prometheus22"

- name: 'alertmananger-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://alertmanager-bot:8080'

- name: "null"
- name: regular_alert_receiver
    <snip>
