#global:

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 60s
  repeat_interval: 60s
  receiver: 'null'

  routes:
  - receiver: email-me
    repeat_interval: 60s

receivers:

- name: email-me
  email_configs:
  - to: vasulrgdevera@gmail.com
    from: team3crashcourse@gmail.com
    smarthost: smtp.gmail.com:25
    auth_username: "team3crashcourse"
    auth_identity: "team3crashcourse@gmail.com"
    auth_password: "prometheus22"

- name: 'alertmananger-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://0.0.0.0:8080'

- name: "null"
- name: regular_alert_receiver
    <snip>
