route:
  receiver: 'alertmananger-bot'
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 60s
  group_by: ['instance']

receivers:

- name: alertmananger-bot
  webhook_configs:
  - send_resolved: false
    url: 'http://prometheus-alertmanager_bot:8080'
