
version: '3'
services:
    prometheus:
        image: prom/prometheus
        volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
        - prometheus_data:/prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
    node-exporter:
        image: prom/node-exporter
        ports:
            - '9100:9100'

    grafana:
            image: grafana/grafana
            environment:
                - GF_SECURITY_ADMIN_PASSWORD=pass
            depends_on:
                - prometheus
            ports:
                - "3000:3000"

    alertmanager:
        image: prom/alertmanager
        volumes:
           - ./alertmanager/alertmanager.yml:/etc/prometheus/alertmanager.yml
        command:
        - '--config.file=/etc/prometheus/alertmanager.yml'
        ports:
            - "9093:9093"


volumes:
    prometheus_data: {}
    grafana_data: {}
