
version: '3'

services:

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/prometheus/alertmanager.yml
    networks:
      - prometheus-network
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
    ports:
      - 9093:9093

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
      - blackbox_exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - prometheus-network

  grafana-ui:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - prometheus-server:prometheus
    volumes:
      - ./camptocamp-prometheus-alertmanager-datasource:/var/lib/grafana/plugins/
    networks:
      - prometheus-network


  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    dns: 8.8.8.8
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - "./prometheus/blackbox.yml:/config"
    networks:
      - prometheus-network
    command: -config.file=/config/blackbox.yml


  telegram-bot:
    container_name: prometheus-alertmanger_bot
    image: metalmatze/alertmanager-bot:0.4.0
    environment:
      ALERTMANAGER_URL: http://prometheus-alertmanager:9093
      BOLT_PATH: /data/bot.db
      STORE: bolt
      TELEGRAM_ADMIN: 42356434523
      TELEGRAM_TOKEN: 1206294097:AAEdYbh1HBZIrCYKGJF0dpZG8moEsr67Dcs
      TEMPLATE_PATHS: /templates/default.tmpl
      LISTEN_ADDR: 0.0.0.0:8080
    volumes:
      - ./prometheus:/data
      - ./prometheus/telegram.tmpl:/templates/default.tmpl
    networks:
      - prometheus-network
    restart: always
  
  networks:
    prometheus-network:
