
version: '3'
services:
    prometheus:
        image: prom/prometheus
        volumes:
            - prometheus_data:/prometheus
        command:
        - '-config.file=/etc/prometheus/prometheus.yml'
        - '-alertmanager.url=http://alertmanager:9093'
        ports:
            - '9090:9090'
    node-exporter:
        image: prom/node-exporter
        ports:
            - '9100:9100'
    grafana:
            image: grafana/grafana
            environment:
                - GF_SECURITY_ADMIN_PASSWORD=pass
            depends_on:
                - prometheus
            ports:
                - "3000:3000"
    alertmanager:
        build: ./alertmanager
        command:
            - '-config.file=/alertmanager.yml'
        ports:
            - "9093:9093"


volumes:
    prometheus_data: {}
    grafana_data: {}
