# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 35s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration


# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules.yml"
  # - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']
      
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 35.230.82.224:9093


  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9100','http://terraform-asg-example-1562246850.us-west-2.elb.amazonaws.com:9100','second_server:9100']
